### ISSUE TITLE
Unable to format with extension

### ISSUE THREAD

**Issue by dac09** [fcrespo82/vscode-markdown-table-formatter#39]
Hi,

Thanks for this great extension - I've definitely used in a few months ago and found it invaluable. However recent versions seems to have stopped working (on just `.md` files). 

Any tips on how to provider better logs for you to debug?

The only errors I see are:

When I try to format:
![image](https://user-images.githubusercontent.com/1521877/116231866-52e71e80-a751-11eb-8cc6-298199f77d50.png)

When I try to use the command pallette:
![image](https://user-images.githubusercontent.com/1521877/116231896-5c708680-a751-11eb-80f1-5f35c67b68e9.png)

And I don't see a format selection option (not sure if it was there before though!)

---
Version: 2.1.5

**Comment by fcrespo82** [comment]
Hi, thanks for the feedback. And sorry for the trouble.

I think I found the bug and the cause.

As a quick workaround. Please, go to the extension page, click on the arrow down on the *Uninstall* button and revert to the last working version. 

I should fix this by the end of the day.

**Comment by fcrespo82** [comment]
Released [v2.1.6](/fcrespo82/vscode-markdown-table-formatter/releases/v2.1.6)

This should fix this bug. If persists, please re-open the same issue.

**Comment by jasonjoh** [comment]
Not sure if it's the same issue, but I have 2.1.6 and I noticed that CTRL+K,CTRL+F was not working for me using the latest VS Code Insiders.

Version: 1.56.0-insider (user setup)
Commit: 13f1afffab09548c10ddb3bc5d5db52587876ad8
Date: 2021-04-28T04:52:06.990Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

I noticed in the status bar when I hit the key combo, it just said `The key combination (CTRL + K, CTRL + F) is not a command.`

I tried running the **Enable for current language** command (even though this is a Markdown file) and got:

```
Command 'Markdown Table Formatter: Enable for current language' resulted in an error (command 'markdown-table-formatter.enableForCurrentScope' not found)
```

Downgrading to 2.1.4 got me working again.

**Comment by fcrespo82** [comment]
Hi @jasonjoh , sorry to hear that.

Since I was unable to replicate this issue, could you please verify a couple of things to help me debug this?

1. Do you have any custom configuration on the extension? Or they are default? 

You can find them going to settings screen and selecting **Markdown Table formatter** extension on the left column under **Extensions**.
<details><summary>Image</summary>
<img width="194" alt="image" src="https://user-images.githubusercontent.com/462171/116491140-920b9180-a86f-11eb-9ece-8082ca541c20.png">
</details>
If you have any custom setting it will show up highlighted in the list.
<details><summary>Example</summary>
In this case "Delimiter Row Padding" have a custom value.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/462171/116491227-cbdc9800-a86f-11eb-99b2-a70d34574cba.png">
</details>

2. Do you have a lot of extensions running? I changed the _Activation Event_ to the known commands and on _Startup Finish_, but running a lot of extensions could hinder the activation and show this message.

3. Test with a simple file like [this](/fcrespo82/vscode-markdown-table-formatter/blob/master/src/test/files/onetable.md)
    It should display the CodeLens above the table like so:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/462171/116492176-00515380-a872-11eb-871d-4fbd377c6ac0.png">

Thanks.

**Comment by jasonjoh** [comment]
Thanks! I have 52 extensions installed. The only custom setting I have on the extension is "Limit Last Column Width", but I actually turned that on after this problem started. 

I just updated back to 2.1.6 and waited until the "Activating Extensions" status finished. I see that the CodeLens does not display in the file I was working with previously, which is not a very large file (71 lines). 

I also tried your simple file and no CodeLens. I also just tried updating the Code Insiders build to today's build (details below), and the problem persists. Finally, I disabled all extensions except this one, and that didn't help.

Version: 1.56.0-insider (user setup)
Commit: 0123d26aaa393bccf99f31f1eac07df6c9e218ce
Date: 2021-04-29T05:14:58.987Z
Electron: 12.0.5
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by jasonjoh** [comment]
I poked around in the output window and found this in the Extension Host Log output:

```
[2021-04-29 08:38:31.650] [exthost] [info] ExtensionService#_doActivateExtension fcrespo82.markdown-table-formatter {"startup":false,"extensionId":{"value":"fcrespo82.markdown-table-formatter","_lower":"fcrespo82.markdown-table-formatter"},"activationEvent":"onStartupFinished"}
[2021-04-29 08:38:31.650] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jasonjoh/.vscode-insiders/extensions/fcrespo82.markdown-table-formatter-2.1.6/out/extension.js
[2021-04-29 08:38:31.659] [exthost] [error] Activating extension fcrespo82.markdown-table-formatter failed due to an error:
[2021-04-29 08:38:31.659] [exthost] [error] Error: Cannot find module 'c:\Users\jasonjoh\.vscode-insiders\extensions\fcrespo82.markdown-table-formatter-2.1.6\out\extension.js'
Require stack:
- c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js
- c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js
- c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.s._load (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:27816)
	at Function.S._load (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:24532)
	at Function.a._load (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:96:58822)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:5:101)
	at d._loadCommonJSModule (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:25941)
	at d._doActivateExtension (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:92:12457)
	at d._activateExtension (c:\Users\jasonjoh\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:92:11516)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

Checking at c:\Users\jasonjoh\.vscode-insiders\extensions, I see there is no `out` directory.

```
    Directory: C:\Users\jasonjoh\.vscode-insiders\extensions\fcrespo82.markdown-table-formatter-2.1.6

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           4/27/2021  2:22 PM                .github
d----           4/27/2021  2:22 PM                resources
-a---           4/27/2021  2:22 PM             52 .eslintignore
-a---           4/27/2021  2:22 PM           2602 .vsixmanifest
-a---           4/27/2021  2:22 PM           4755 CHANGELOG.md
-a---           4/29/2021  8:16 AM           6790 package.json
-a---           4/27/2021  2:22 PM           1453 publish
-a---           4/27/2021  2:22 PM           3524 README.md
```

**Comment by fcrespo82** [comment]
Hi again @jasonjoh .

Thank you, you went above and beyond to help me with this.

I found the bug... Since I changed the bundler from web pack to esbuild it changed where the code is stored, and that folder was on an ignore list.

Version 2.1.7 should fix this for real....
